# Generated by Django 4.1.2 on 2022-10-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityu_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folder',
            new_name='docfile',
        ),
    ]
