# Generated by Django 4.1.2 on 2022-10-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityu_app', '0002_rename_folder_folder_docfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
