# Generated by Django 4.1.2 on 2022-10-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityu_app', '0005_rename_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='imagefile',
            field=models.FileField(upload_to='./media/CityU_POD'),
        ),
    ]
