# Generated by Django 4.1.2 on 2022-10-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityu_app', '0006_excel_alter_image_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Png',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pngfile', models.FileField(upload_to='./CityU_POD')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
